import { Customer } from "../types";

export const customers = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    cccd: "123456789",
    address: "Hà Nội",
    phone: "0901234567",
    bookings: 3,
    reviews: 2,
    active: true,
  },
  {
    id: 2,
    name: "Trần Thị B",
    cccd: "987654321",
    address: "TP. Hồ Chí Minh",
    phone: "0912345678",
    bookings: 5,
    reviews: 4,
    active: false,
  },
  {
    id: 3,
    name: "Lê Văn C",
    cccd: "192837465",
    address: "Đà Nẵng",
    phone: "0923456789",
    bookings: 2,
    reviews: 0,
    active: true,
  },
  {
    id: 4,
    name: "Phạm Thị D",
    cccd: "564738291",
    address: "Cần Thơ",
    phone: "0934567890",
    bookings: 7,
    reviews: 5,
    active: true,
  },
  {
    id: 5,
    name: "Đỗ Văn E",
    cccd: "837261945",
    address: "Hải Phòng",
    phone: "0945678901",
    bookings: 1,
    reviews: 0,
    active: false,
  },
  {
    id: 6,
    name: "Hoàng Thị F",
    cccd: "123987456",
    address: "Huế",
    phone: "0956789012",
    bookings: 6,
    reviews: 3,
    active: true,
  },
  {
    id: 7,
    name: "Vũ Văn G",
    cccd: "456123789",
    address: "Nha Trang",
    phone: "0967890123",
    bookings: 4,
    reviews: 1,
    active: false,
  },
  {
    id: 8,
    name: "Bùi Thị H",
    cccd: "789456123",
    address: "Buôn Ma Thuột",
    phone: "0978901234",
    bookings: 3,
    reviews: 2,
    active: true,
  },
  {
    id: 9,
    name: "Ngô Văn I",
    cccd: "321654987",
    address: "Biên Hòa",
    phone: "0989012345",
    bookings: 2,
    reviews: 1,
    active: false,
  },
  {
    id: 10,
    name: "Đinh Thị J",
    cccd: "654789321",
    address: "Vũng Tàu",
    phone: "0990123456",
    bookings: 8,
    reviews: 6,
    active: true,
  },
];
export const customerColumns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "name", headerName: "Tên khách hàng", width: 200 },
  { field: "cccd", headerName: "CCCD/CMND", width: 150 },
  { field: "address", headerName: "Địa chỉ", width: 200 },
  { field: "phone", headerName: "Số điện thoại", width: 150 },
  { field: "bookings", headerName: "Số lần đặt sân", width: 150 },
  { field: "reviews", headerName: "Số đánh giá", width: 150 },
  {
    field: "active",
    headerName: "Trạng thái",
    width: 120,
    renderCell: (params: { row: Customer }) =>
      params.row.active ? "Kích hoạt" : "Khóa",
  },
];

export const customerFilterOptions = [
  { value: "", label: "Tất cả" },
  { value: "active", label: "Kích hoạt" },
  { value: "inactive", label: "Khóa" },
];
